## SPOTIFY

INTENTO DE JUNTAR TODAS LAS FUNCIONES DE SPOTIFY PARA TENER 1 SOLO CODIGO FINAL

In [ ]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import time
import requests, time, re, html
from io import BytesIO

import os
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy
from dotenv import load_dotenv

In [ ]:
load_dotenv()

# Autenticación
client_id = os.getenv("SPOTIFY_CLIENT_ID")
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")

auth_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(auth_manager=auth_manager)

**Extracción de Datos de la API de SPOTIFY**

In [3]:
años = range(2015, 2020)  # 2015, 2016, 2017, 2018, 2019
myoffset = range(0,150,50) 
generos = ['soundtrack','k-pop','electronic','afro']

In [4]:
lista_canciones = [] # Creación de una lista para integrar todos los diccionarios que se generan en el bucle.

for g in generos:
    genres_dic = {}  # Creación de un diccionario por género.

    for año in años:
        for o in myoffset:
            print(f"Buscando {g} - {año} - offset {o}")
            datos = sp.search(q=f"genre:{g}, year:{año}", type="track", limit=50, offset=o)

            # acceso seguro a los datos
            tracks = datos.get('tracks', {}).get('items', [])

            for track in tracks:
                cancion = {
                    "id": track['id'],
                    "track_name": track['name'],
                    "artist_name": track['artists'][0]['name'],
                    "year": año,
                    "genre": g,
                    "album_type": track['album']['album_type'],
                    "release_date": track['album']['release_date'],
                    "popularity": track['popularity']
                } # Información de cada canción según los parametros explicitos

                lista_canciones.append(cancion)  # Agregación de cada canción extraida a la lista general
                genres_dic[track['id']] = cancion  # Contador de canciones por genero

    print(f"Total canciones para {g}: {len(genres_dic)}")

Buscando soundtrack - 2015 - offset 0
Buscando soundtrack - 2015 - offset 50
Buscando soundtrack - 2015 - offset 100
Buscando soundtrack - 2016 - offset 0
Buscando soundtrack - 2016 - offset 50
Buscando soundtrack - 2016 - offset 100
Buscando soundtrack - 2017 - offset 0
Buscando soundtrack - 2017 - offset 50
Buscando soundtrack - 2017 - offset 100
Buscando soundtrack - 2018 - offset 0
Buscando soundtrack - 2018 - offset 50
Buscando soundtrack - 2018 - offset 100
Buscando soundtrack - 2019 - offset 0
Buscando soundtrack - 2019 - offset 50
Buscando soundtrack - 2019 - offset 100
Total canciones para soundtrack: 750
Buscando k-pop - 2015 - offset 0
Buscando k-pop - 2015 - offset 50
Buscando k-pop - 2015 - offset 100
Buscando k-pop - 2016 - offset 0
Buscando k-pop - 2016 - offset 50
Buscando k-pop - 2016 - offset 100
Buscando k-pop - 2017 - offset 0
Buscando k-pop - 2017 - offset 50
Buscando k-pop - 2017 - offset 100
Buscando k-pop - 2018 - offset 0
Buscando k-pop - 2018 - offset 50
Buscando k-pop - 2018 - offset 100
Buscando k-pop - 2019 - offset 0
Buscando k-pop - 2019 - offset 50
Buscando k-pop - 2019 - offset 100
Total canciones para k-pop: 692
Buscando electronic - 2015 - offset 0
Buscando electronic - 2015 - offset 50
Buscando electronic - 2015 - offset 100
Buscando electronic - 2016 - offset 0
Buscando electronic - 2016 - offset 50
Buscando electronic - 2016 - offset 100
Buscando electronic - 2017 - offset 0
Buscando electronic - 2017 - offset 50
Buscando electronic - 2017 - offset 100
Buscando electronic - 2018 - offset 0
Buscando electronic - 2018 - offset 50
Buscando electronic - 2018 - offset 100
Buscando electronic - 2019 - offset 0
Buscando electronic - 2019 - offset 50
Buscando electronic - 2019 - offset 100
Total canciones para electronic: 750
Buscando afro - 2015 - offset 0
Buscando afro - 2015 - offset 50
Buscando afro - 2015 - offset 100
Buscando afro - 2016 - offset 0
Buscando afro - 2016 - offset 50
Buscando afro - 2016 - offset 100
Buscando afro - 2017 - offset 0
Buscando afro - 2017 - offset 50
Buscando afro - 2017 - offset 100
Buscando afro - 2018 - offset 0
Buscando afro - 2018 - offset 50
Buscando afro - 2018 - offset 100
Buscando afro - 2019 - offset 0
Buscando afro - 2019 - offset 50
Buscando afro - 2019 - offset 100
Total canciones para afro: 750

In [5]:
genres_dic # Diccionario de canciones

{'5bPpNuK3qgt1UbI18QEUYx': {'id': '5bPpNuK3qgt1UbI18QEUYx',
  'track_name': 'Final (Baba Nla)',
  'artist_name': 'Wizkid',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-12-10',
  'popularity': 52},
 '0TlHywt8QI15kDuJd7SRnL': {'id': '0TlHywt8QI15kDuJd7SRnL',
  'track_name': 'The Money',
  'artist_name': 'Davido',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-11-07',
  'popularity': 49},
 '7rQ6DH09HApIzk80dNSGEy': {'id': '7rQ6DH09HApIzk80dNSGEy',
  'track_name': 'Baby Hello',
  'artist_name': 'Wande Coal',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-10-24',
  'popularity': 40},
 '5V7DFLUcl82jErKWngCon7': {'id': '5V7DFLUcl82jErKWngCon7',
  'track_name': 'Não Vai',
  'artist_name': 'Djodje',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-12-07',
  'popularity': 44},
 '5mLjOzvBL124hjJsoT6Ctz': {'id': '5mLjOzvBL124hjJsoT6Ctz',
  'track_name': 'Woju (Remix) [feat. Davido & Tiwa Savage]',
  'artist_name': 'Kizz Daniel',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-02-28',
  'popularity': 51},
 '2yVRTP32nLGbJtSh884QId': {'id': '2yVRTP32nLGbJtSh884QId',
  'track_name': 'Balaumba',
  'artist_name': 'Bebi Philip',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-01-21',
  'popularity': 34},
 '4SJjVlVRiNTLoN2RV6qezS': {'id': '4SJjVlVRiNTLoN2RV6qezS',
  'track_name': 'Teu Fã',
  'artist_name': 'Master Jake',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-08-10',
  'popularity': 42},
 '7AJbTEBoDJ3VtqYRAbjyXE': {'id': '7AJbTEBoDJ3VtqYRAbjyXE',
  'track_name': 'Applaudise',
  'artist_name': 'Iyanya',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-04-19',
  'popularity': 41},
 '01YF5yNYziZUHqE6ZTEQMk': {'id': '01YF5yNYziZUHqE6ZTEQMk',
  'track_name': 'Liberian Girl',
  'artist_name': 'Ruff-N-Smooth',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-03-23',
  'popularity': 27},
 '439o6N0vgQUhUGkOjldYFV': {'id': '439o6N0vgQUhUGkOjldYFV',
  'track_name': 'Starboy - Soco',
  'artist_name': 'Eugy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-12-07',
  'popularity': 35},
 '6oh9lVADxruCxcEWQUdSAl': {'id': '6oh9lVADxruCxcEWQUdSAl',
  'track_name': 'Move Dadass',
  'artist_name': 'Bebi Philip',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015',
  'popularity': 37},
 '751Xx8KrPrMO4ifcEoszAJ': {'id': '751Xx8KrPrMO4ifcEoszAJ',
  'track_name': 'Já Decidi',
  'artist_name': 'Boy Teddy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 51},
 '7qeh3o6nW5XCZZjbMCEVWd': {'id': '7qeh3o6nW5XCZZjbMCEVWd',
  'track_name': 'Fica Parado (feat. C4 Pedro)',
  'artist_name': 'Pérola',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-06-26',
  'popularity': 30},
 '2xdEKJ1YHSaa6G3u0idz2i': {'id': '2xdEKJ1YHSaa6G3u0idz2i',
  'track_name': 'Soleil au réveil',
  'artist_name': 'DjeuhDjoah',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-06',
  'popularity': 29},
 '3wgRc4Rkba9wxgJ8gxgX8I': {'id': '3wgRc4Rkba9wxgJ8gxgX8I',
  'track_name': 'Jajão (feat. Eddy Flow)',
  'artist_name': 'Master Jake',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-04-09',
  'popularity': 32},
 '3W54juZUAjga2C5OSI2ezM': {'id': '3W54juZUAjga2C5OSI2ezM',
  'track_name': 'No Limão',
  'artist_name': 'Ravidson',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-05-20',
  'popularity': 40},
 '5HNBUeJfusYS3P3fMKKMUZ': {'id': '5HNBUeJfusYS3P3fMKKMUZ',
  'track_name': 'Vou Tirar O Pé',
  'artist_name': 'Dream Boyz',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-10-18',
  'popularity': 42},
 '3Px454rzMHtIRc9R04QSlB': {'id': '3Px454rzMHtIRc9R04QSlB',
  'track_name': 'Soleil Couchant',
  'artist_name': 'The Souljazz Orchestra',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-04',
  'popularity': 25},
 '5Uplcn5jaouEBHKBZbjyS8': {'id': '5Uplcn5jaouEBHKBZbjyS8',
  'track_name': 'Lento Kizomba',
  'artist_name': 'SERGIO CREMONESE',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-02-25',
  'popularity': 28},
 '2rPRTmhTRoYBCataK79gfM': {'id': '2rPRTmhTRoYBCataK79gfM',
  'track_name': 'I Concur',
  'artist_name': 'Timaya',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-08-15',
  'popularity': 41},
 '2MUkw4KIzDBVE0toHWHgFY': {'id': '2MUkw4KIzDBVE0toHWHgFY',
  'track_name': 'Wash',
  'artist_name': 'Tekno',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-11-20',
  'popularity': 49},
 '2nCbegqI9petdYpSvbfzeF': {'id': '2nCbegqI9petdYpSvbfzeF',
  'track_name': 'I Need You So',
  'artist_name': 'Jennifer Dias',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-07-12',
  'popularity': 33},
 '0n9GgL4cSILLVQkCng8w4O': {'id': '0n9GgL4cSILLVQkCng8w4O',
  'track_name': 'African Scream - Marimbas',
  'artist_name': 'Dotorado Pro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-04-20',
  'popularity': 35},
 '1McHU7TbeVZsSMQb4UCG0B': {'id': '1McHU7TbeVZsSMQb4UCG0B',
  'track_name': 'Khomo Tsaka Deile Kae?',
  'artist_name': 'Marumo',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-03-09',
  'popularity': 36},
 '4gvDUHpTEiVHhDeeobenz4': {'id': '4gvDUHpTEiVHhDeeobenz4',
  'track_name': 'Você Me Kuia',
  'artist_name': 'Jay Oliver',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-23',
  'popularity': 45},
 '4PZsmNaGJHZamk5QIXI6Zi': {'id': '4PZsmNaGJHZamk5QIXI6Zi',
  'track_name': 'Kizomba',
  'artist_name': 'Don Miguelo',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-05-18',
  'popularity': 29},
 '7qWszdYQHJUXLmlmDgWyqp': {'id': '7qWszdYQHJUXLmlmDgWyqp',
  'track_name': 'Ms. Killa',
  'artist_name': 'Mykel Forever',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-10-31',
  'popularity': 31},
 '1AeakTSnBi5waUXkP1CcRa': {'id': '1AeakTSnBi5waUXkP1CcRa',
  'track_name': 'You No Fit Touch Am - Medlar Remix',
  'artist_name': 'Dele Sosimi',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-11-20',
  'popularity': 35},
 '5fobKrmWA5owgI5u8EcXSs': {'id': '5fobKrmWA5owgI5u8EcXSs',
  'track_name': 'Mama Africa',
  'artist_name': 'Bracket',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 50},
 '0xaKMeeB2gU0DYtoA3ZqZN': {'id': '0xaKMeeB2gU0DYtoA3ZqZN',
  'track_name': 'Panya (feat. Tekno)',
  'artist_name': 'Bracket',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 40},
 '0rauOsfmlYgBGkWFc4NHft': {'id': '0rauOsfmlYgBGkWFc4NHft',
  'track_name': 'Number One',
  'artist_name': 'Boy Teddy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 49},
 '6y4nqlHb6WXmHkv3Pa7n3P': {'id': '6y4nqlHb6WXmHkv3Pa7n3P',
  'track_name': 'Adonai (Remix) [feat. Castro]',
  'artist_name': 'Sarkodie',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-06-17',
  'popularity': 49},
 '50Il1iztFbjifqKLvBovQ9': {'id': '50Il1iztFbjifqKLvBovQ9',
  'track_name': 'Deixa o Mundo Falar',
  'artist_name': 'Jey V',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-10-23',
  'popularity': 47},
 '09fpuM4rl4UKthCkoI4wHE': {'id': '09fpuM4rl4UKthCkoI4wHE',
  'track_name': 'Não me Pede',
  'artist_name': 'C4 Pedro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 35},
 '5MAScTGPHzWAeivPjpATa9': {'id': '5MAScTGPHzWAeivPjpATa9',
  'track_name': 'My Woman, My Everything (feat. Wandecoal)',
  'artist_name': 'Patoranking',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-07-06',
  'popularity': 53},
 '43C8ga8Z7MkOc1TmEzXcJ3': {'id': '43C8ga8Z7MkOc1TmEzXcJ3',
  'track_name': 'Skin Tight',
  'artist_name': 'Mr Eazi',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-08-31',
  'popularity': 54},
 '5JrT4NhJkLGTKoIiPani66': {'id': '5JrT4NhJkLGTKoIiPani66',
  'track_name': 'De Alma na Paixão',
  'artist_name': 'Yuri da Cunha',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-06-29',
  'popularity': 40},
 '5nXSUlaOCd4sFVHMyjpaDB': {'id': '5nXSUlaOCd4sFVHMyjpaDB',
  'track_name': 'Leva-Me',
  'artist_name': 'Daddy Killa',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015',
  'popularity': 33},
 '4t59zVbRoCgnvyQ9hM3xP1': {'id': '4t59zVbRoCgnvyQ9hM3xP1',
  'track_name': 'Duro',
  'artist_name': 'Tekno',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-06-22',
  'popularity': 55},
 '6sAukzDGVFKv3Z6dF3pU9X': {'id': '6sAukzDGVFKv3Z6dF3pU9X',
  'track_name': 'Vamos Ficar por Aqui',
  'artist_name': 'C4 Pedro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 50},
 '3AxKlhbCVMwrDbP4laSyys': {'id': '3AxKlhbCVMwrDbP4laSyys',
  'track_name': 'Tu És a Mulher',
  'artist_name': 'C4 Pedro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 49},
 '4QsX4JEgXl0G4oQabHQ722': {'id': '4QsX4JEgXl0G4oQabHQ722',
  'track_name': 'Me Agarra Só No Uhm',
  'artist_name': 'Landrick',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-08',
  'popularity': 40},
 '6YPwVMy9U1zFC1KjkyP61j': {'id': '6YPwVMy9U1zFC1KjkyP61j',
  'track_name': 'Go Back',
  'artist_name': 'Tony Allen',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-02-02',
  'popularity': 39},
 '7LtfpklIMpsU0tWw0EbIOl': {'id': '7LtfpklIMpsU0tWw0EbIOl',
  'track_name': 'Tudo por Amor',
  'artist_name': 'Calema',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-08-20',
  'popularity': 47},
 '4msISwT8zsgxLu5MBiZeSO': {'id': '4msISwT8zsgxLu5MBiZeSO',
  'track_name': 'Tout le monde pense',
  'artist_name': 'DjeuhDjoah',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-06',
  'popularity': 38},
 '38jKUBFw5V1vIZ502v4HLM': {'id': '38jKUBFw5V1vIZ502v4HLM',
  'track_name': 'Bailar Kizomba',
  'artist_name': 'Grupo Extra',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-01-01',
  'popularity': 27},
 '24P6e3t7SxFdyqKFM0Ha33': {'id': '24P6e3t7SxFdyqKFM0Ha33',
  'track_name': 'Shake Body - French',
  'artist_name': 'Skales',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-05-18',
  'popularity': 37},
 '3mNtJ94LS5gTrclSCE9w9r': {'id': '3mNtJ94LS5gTrclSCE9w9r',
  'track_name': "Eye Nyam Nam 'A' Mensuro - Henrik Schwarz Blend",
  'artist_name': 'Ebo Taylor',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-07-24',
  'popularity': 43},
 '0VRv4f0FS0XBp9qXzWAd8c': {'id': '0VRv4f0FS0XBp9qXzWAd8c',
  'track_name': 'Kossa Kossa',
  'artist_name': 'The Souljazz Orchestra',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-04',
  'popularity': 47},
 '1agLiWjSBYSTsKZLudOunC': {'id': '1agLiWjSBYSTsKZLudOunC',
  'track_name': 'Shake Body',
  'artist_name': 'Skales',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-05-18',
  'popularity': 69},
 '5RC1M4mO6atWy7g4U8Tsn8': {'id': '5RC1M4mO6atWy7g4U8Tsn8',
  'track_name': 'Fans Mi',
  'artist_name': 'Davido',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-06-09',
  'popularity': 43},
 '4bzS0aUqNJIKiXk86k4tol': {'id': '4bzS0aUqNJIKiXk86k4tol',
  'track_name': 'Soke',
  'artist_name': 'Burna Boy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-03-13',
  'popularity': 47},
 '4SDWiUHywJQrIY7zsjZNHm': {'id': '4SDWiUHywJQrIY7zsjZNHm',
  'track_name': 'Soldier',
  'artist_name': 'Falz',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-11-16',
  'popularity': 50},
 '7qecdQmvEVTmpJQMjteuVW': {'id': '7qecdQmvEVTmpJQMjteuVW',
  'track_name': 'Hollup',
  'artist_name': 'Mr Eazi',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-12-05',
  'popularity': 44},
 '2F21BqgPX0wsmFjNs9ghPz': {'id': '2F21BqgPX0wsmFjNs9ghPz',
  'track_name': 'Dodo',
  'artist_name': 'Davido',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-09-21',
  'popularity': 48},
 '1xMj8OCAN3atp4tcdY4MiM': {'id': '1xMj8OCAN3atp4tcdY4MiM',
  'track_name': 'Godwin',
  'artist_name': 'Korede Bello',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-01-29',
  'popularity': 40},
 '00q5d8viqDkGYbGmZEuHbM': {'id': '00q5d8viqDkGYbGmZEuHbM',
  'track_name': 'Ene Menye',
  'artist_name': 'Dada KD',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-24',
  'popularity': 33},
 '67VH1BYRIMjGj3fZQBHDS2': {'id': '67VH1BYRIMjGj3fZQBHDS2',
  'track_name': 'Remue la bouteille',
  'artist_name': 'Kedjevara',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-12-15',
  'popularity': 35},
 '5FLz4y3naxkboozWw7vO8F': {'id': '5FLz4y3naxkboozWw7vO8F',
  'track_name': 'Greet The Dawn',
  'artist_name': 'The Souljazz Orchestra',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-04',
  'popularity': 24},
 '2lxUiTHbaoWL0opbZ6MEq2': {'id': '2lxUiTHbaoWL0opbZ6MEq2',
  'track_name': 'Love Me for Real',
  'artist_name': 'Rim Kwaku Obeng',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-10-02',
  'popularity': 31},
 '4rlp9tyP0TSx0wvTaK92dv': {'id': '4rlp9tyP0TSx0wvTaK92dv',
  'track_name': 'Afrofunk Revolution',
  'artist_name': 'IFÁ',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-08-19',
  'popularity': 28},
 '5ilfABgGhOIqPn698IFjfV': {'id': '5ilfABgGhOIqPn698IFjfV',
  'track_name': 'So Mi Ma Bo',
  'artist_name': 'Jay Oliver',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-23',
  'popularity': 38},
 '7ij7CEIZUovjn0974uae2b': {'id': '7ij7CEIZUovjn0974uae2b',
  'track_name': 'Nana',
  'artist_name': 'Bracket',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 30},
 '7CvTWp0bLIHWlvJ4Eh7aVo': {'id': '7CvTWp0bLIHWlvJ4Eh7aVo',
  'track_name': 'Rotate',
  'artist_name': 'Wande Coal',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-04',
  'popularity': 41},
 '2qQsQUw8WYynynB274Iyie': {'id': '2qQsQUw8WYynynB274Iyie',
  'track_name': 'Side 2 Side',
  'artist_name': 'Saaphy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-12-17',
  'popularity': 22},
 '1R2h72zYCwAN7bJAuPmaG4': {'id': '1R2h72zYCwAN7bJAuPmaG4',
  'track_name': 'Quelle folle idée',
  'artist_name': 'DjeuhDjoah',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-04-06',
  'popularity': 25},
 '58tROf9Y6cC3xJdCIg9BRv': {'id': '58tROf9Y6cC3xJdCIg9BRv',
  'track_name': 'Mawa naya',
  'artist_name': 'Serge Beynaud',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-11-16',
  'popularity': 30},
 '5BAkyOIIB5F1v2qDvo2wxD': {'id': '5BAkyOIIB5F1v2qDvo2wxD',
  'track_name': 'Gostosa',
  'artist_name': 'Daduh King',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-10-12',
  'popularity': 37},
 '6bnlz07v3DbHtMrXJcGESW': {'id': '6bnlz07v3DbHtMrXJcGESW',
  'track_name': 'Casa Comigo',
  'artist_name': 'Ravidson',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-05-20',
  'popularity': 34},
 '01n9OfbVlKemg1PmUb5yKt': {'id': '01n9OfbVlKemg1PmUb5yKt',
  'track_name': 'O Teu Corpo',
  'artist_name': 'Boy Teddy',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-20',
  'popularity': 38},
 '71rteIjW3xXCMjK9h1ugv8': {'id': '71rteIjW3xXCMjK9h1ugv8',
  'track_name': 'Fouinta Fouinte',
  'artist_name': 'Serge Beynaud',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-02-11',
  'popularity': 33},
 '4HFYoXRa8sqSm88GF0G2ae': {'id': '4HFYoXRa8sqSm88GF0G2ae',
  'track_name': 'Vote',
  'artist_name': 'Leo Beatz',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-12-22',
  'popularity': 30},
 '7eaBubQrTkzcIksYBYspeC': {'id': '7eaBubQrTkzcIksYBYspeC',
  'track_name': 'Ama-Rulah',
  'artist_name': 'Roberto',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-10-14',
  'popularity': 39},
 '6Xy9G0IFR2Hz85rMBuG0hJ': {'id': '6Xy9G0IFR2Hz85rMBuG0hJ',
  'track_name': 'Uma Em um Milhão',
  'artist_name': '2Much',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-29',
  'popularity': 37},
 '4hvUYAEp6xTdwMI3M4W5nF': {'id': '4hvUYAEp6xTdwMI3M4W5nF',
  'track_name': 'Ogede',
  'artist_name': 'Orezi',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-08',
  'popularity': 40},
 '7azleZzqOJg3DyIh86zQf7': {'id': '7azleZzqOJg3DyIh86zQf7',
  'track_name': 'Fila da Goda',
  'artist_name': 'Landrick',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-07-08',
  'popularity': 27},
 '6K4mkIv9jq5khtrDLXRhI4': {'id': '6K4mkIv9jq5khtrDLXRhI4',
  'track_name': 'Crache La Douleur',
  'artist_name': 'Fanga',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-10-01',
  'popularity': 27},
 '4pW5ouflRE2QOg885hAtjF': {'id': '4pW5ouflRE2QOg885hAtjF',
  'track_name': 'The Sound',
  'artist_name': 'Davido',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-01-30',
  'popularity': 43},
 '0tXjdxP16Xee1wBNo9CZCK': {'id': '0tXjdxP16Xee1wBNo9CZCK',
  'track_name': 'Alkayida',
  'artist_name': 'KCee',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-09-07',
  'popularity': 26},
 '373yfcJIQzEZax2DvIrshF': {'id': '373yfcJIQzEZax2DvIrshF',
  'track_name': 'Banguere - Original Mix',
  'artist_name': 'Pablo Fierro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-05-01',
  'popularity': 17},
 '6EiOr8CpboBVl86mnBCGg6': {'id': '6EiOr8CpboBVl86mnBCGg6',
  'track_name': 'Segunda Mão (feat. Landrick)',
  'artist_name': 'Zona 5',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-05-01',
  'popularity': 41},
 '10vaiZmtfbi4peF33u2fmP': {'id': '10vaiZmtfbi4peF33u2fmP',
  'track_name': 'La Vie En Rose - Kizomba Version',
  'artist_name': 'Gino Latino DJ',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'compilation',
  'release_date': '2015-12-11',
  'popularity': 13},
 '03hnjC8kAVy9tmfgcB0p0y': {'id': '03hnjC8kAVy9tmfgcB0p0y',
  'track_name': 'Love Again (feat. Sauti Sol)',
  'artist_name': 'C4 Pedro',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'single',
  'release_date': '2015-06-09',
  'popularity': 35},
 '55vXTF5Pv3UoyaixvbBkQp': {'id': '55vXTF5Pv3UoyaixvbBkQp',
  'track_name': 'Always on My Mind (feat. Obrafour)',
  'artist_name': 'Sarkodie',
  'year': 2015,
  'genre': 'afro',
  'album_type': 'album',
  'release_date': '2015-09-12',

In [6]:
lista_canciones # Lista de diccionarios de canciones

[{'id': '1WHNqqRWhJVZIdCScFKtl5',
  'track_name': 'Washington on Your Side',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 66},
 {'id': '1DLfR4MOfLYbV6v3xrmWa8',
  'track_name': 'We Know',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 66},
 {'id': '2AtC6i0b8TjpjhWBZYLprX',
  'track_name': 'Bonetrousle',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 58},
 {'id': '6oF8ueLn5hIl4PRp17sxW6',
  'track_name': 'That Would Be Enough',
  'artist_name': 'Phillipa Soo',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '46YSff2Rq1ZtN1YVk5cwbZ',
  'track_name': 'Brave Shine',
  'artist_name': 'Aimer',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-07-29',
  'popularity': 61},
 {'id': '7D1Lf7N7AtCuEq5PGJtIPz',
  'track_name': 'The Reynolds Pamphlet',
  'artist_name': 'Original Broadway Cast of Hamilton',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '39IOkz6LpC1qc5Wnt0T07r',
  'track_name': 'Dance of the Druids (feat. Raya Yarbrough)',
  'artist_name': 'Bear McCreary',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-02-10',
  'popularity': 53},
 {'id': '1llkMtLL4vbe0pr3NV2ckg',
  'track_name': 'Let Me Hear',
  'artist_name': 'Fear, and Loathing in Las Vegas',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-30',
  'popularity': 59},
 {'id': '1CzeuSrm71wHP9qsjg7p3F',
  'track_name': 'The Story of Tonight - Reprise',
  'artist_name': 'Okieriete Onaodowan',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '0w5CRIokPrQAAq7OdIKesr',
  'track_name': 'SAVE The World',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 59},
 {'id': '3lXyAQ0kekAvY5LodpWmUs',
  'track_name': 'Ten Duel Commandments',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '0LpHC9mhPAQC98IjXZIrif',
  'track_name': 'The Election of 1800',
  'artist_name': 'Daveed Diggs',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 66},
 {'id': '27MB0qHaYAZiTlwg25js1Y',
  'track_name': 'Stay Alive',
  'artist_name': 'Original Broadway Cast of Hamilton',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '7m9XR7FquXLP1FewdAcNS9',
  'track_name': 'Guns and Ships',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 72},
 {'id': '2W9u3whoCkQYOUbmnSrHi1',
  'track_name': "What'd I Miss",
  'artist_name': 'Daveed Diggs',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '1mGO8rwCE9zk7H06OxcU5m',
  'track_name': 'History Has Its Eyes on You',
  'artist_name': 'Christopher Jackson',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '733tju3KUeatsbjcTRQ04i',
  'track_name': 'Yorktown (The World Turned Upside Down)',
  'artist_name': 'Original Broadway Cast of Hamilton',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '5z4vmar50qPl80GjIrPBXm',
  'track_name': "It's Raining Somewhere Else",
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 61},
 {'id': '0NJWhm3hUwIZSy5s0TGJ8q',
  'track_name': 'The Story of Tonight',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '3D4J0o9w44QKFrBrYrSVJY',
  'track_name': 'What Comes Next?',
  'artist_name': 'Jonathan Groff',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '7qfoq1JFKBUEIvhqOHzuqX',
  'track_name': 'Non-Stop',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 73},
 {'id': '26lWYpgbcknITI0Fy1eZDs',
  'track_name': 'sans.',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 58},
 {'id': '4kNKL8kCCV3vt9U2k28Lyx',
  'track_name': 'Finale',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 68},
 {'id': '6SHI6STEW51cQkAXBRpLNj',
  'track_name': 'Your Obedient Servant',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '3aiGshuqYhdBBBhHqRf6jn',
  'track_name': 'Spider Dance',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 61},
 {'id': '3nJYcY9yvKP8Oi2Ml8brXt',
  'track_name': 'Right Hand Man',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 69},
 {'id': '2qFIJT5hjqaNFA1GKwl9me',
  'track_name': 'Take a Break',
  'artist_name': 'Phillipa Soo',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 67},
 {'id': '0wae8KoprNjfrXWjYYHGy9',
  'track_name': 'Spear of Justice',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 59},
 {'id': '3s9itRgJYcKhem01P17865',
  'track_name': 'Say No to This',
  'artist_name': 'Jasmine Cephas-Jones',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 69},
 {'id': '7EsSVPxaYoAZjQwhspJBs2',
  'track_name': 'Who Lives, Who Dies, Who Tells Your Story',
  'artist_name': 'Original Broadway Cast of Hamilton',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '7BGZ27yeaKR5OZOIxyegZi',
  'track_name': 'Death By Glamour',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 67},
 {'id': '2yBMVrq96wb9OHbMdBs0lF',
  'track_name': "A Winter's Ball",
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 69},
 {'id': '2TK2KSrzXD6W01qjXVjNGh',
  'track_name': 'The Room Where It Happens',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 71},
 {'id': '2G9lekfCh83S0lt2yfffBz',
  'track_name': 'Farmer Refuted',
  'artist_name': 'Thayne Jasperson',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 68},
 {'id': '7EqpEBPOohgk7NnKvBGFWo',
  'track_name': 'Wait for It',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 75},
 {'id': '1di1C0QI6Y92yZPYn6XYAZ',
  'track_name': 'シルエット',
  'artist_name': 'KANA-BOON',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-01-21',
  'popularity': 73},
 {'id': '3eTgg18rKBD30Hef1gv0wz',
  'track_name': 'Bundle of Joy',
  'artist_name': 'Michael Giacchino',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-01-01',
  'popularity': 63},
 {'id': '2sEq2rC3ynYsT49x7utWnd',
  'track_name': 'Dear Theodosia',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 69},
 {'id': '6OG1S805gIrH5nAQbEOPY3',
  'track_name': "You'll Be Back",
  'artist_name': 'Jonathan Groff',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 72},
 {'id': '4cxvludVmQxryrnx1m9FqL',
  'track_name': 'My Shot',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 72},
 {'id': '2BlDX1yfT0ea5wo0vjCKKa',
  'track_name': '光るなら',
  'artist_name': 'Goose house',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-02-25',
  'popularity': 67},
 {'id': '71X7bPDljJHrmEGYCe7kQ8',
  'track_name': 'The Schuyler Sisters',
  'artist_name': 'Renée Elise Goldsberry',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 73},
 {'id': '7dqdXqoK6PgNu6ckD0Sxhu',
  'track_name': "Rey's Theme",
  'artist_name': 'John Williams',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-12-18',
  'popularity': 32},
 {'id': '6YnPqvc66bdYGGOJIlDEz1',
  'track_name': 'Battle Against A True Hero',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 61},
 {'id': '7CMVo848b9LsUtVavIoiXC',
  'track_name': 'Hopes And Dreams',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 64},
 {'id': '6dr7ekfhlbquvsVY8D7gyk',
  'track_name': 'Aaron Burr, Sir',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 72},
 {'id': '54Sc7mZQ1RM03STpk4SfaA',
  'track_name': 'Helpless',
  'artist_name': 'Phillipa Soo',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 72},
 {'id': '3RQPR2TN3DIj4dqDUEE2LO',
  'track_name': 'Outlander - The Skye Boat Song (Castle Leoch Version) [feat. Raya Yarbrough]',
  'artist_name': 'Bear McCreary',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-02-10',
  'popularity': 55},
 {'id': '0ybMBs8mKdAP9WSnFTiZvs',
  'track_name': 'ASGORE',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 67},
 {'id': '4TTV7EcfroSLWzXRY6gLv6',
  'track_name': 'Alexander Hamilton',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 74},
 {'id': '723rnBXRc09umUfsasI6Cd',
  'track_name': 'Your Best Nightmare',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 56},
 {'id': '2N2lDDaucbMUw1I1GxBrbc',
  'track_name': 'Waterfall',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 57},
 {'id': '6lsFGDo1IEEPFKh94c9kFe',
  'track_name': 'Blow Us All Away',
  'artist_name': 'Ariana DeBose',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 62},
 {'id': '3KsJYk6EDfkDZZM7CWcLWA',
  'track_name': 'Last Goodbye',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 56},
 {'id': '3eQijz4pPT7rb020LqdhdX',
  'track_name': 'Another Medium',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 56},
 {'id': '4OOA9mtwTevG39jcALusOu',
  'track_name': 'Song That Might Play When You Fight Sans',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 54},
 {'id': '46A71ZDLPRIFCppAdV2W6j',
  'track_name': 'His Theme',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 56},
 {'id': '4XX5uZb9PvTKh8Nm2KSJfk',
  'track_name': 'Once Upon a Time',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 56},
 {'id': '3aDH2C8MwdlxlFSI0B7f0F',
  'track_name': 'Welcome to Jurassic World',
  'artist_name': 'Michael Giacchino',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-06-09',
  'popularity': 50},
 {'id': '1dZutYKh4BtPlxbC81wV34',
  'track_name': 'Best of Wives and Best of Women',
  'artist_name': 'Phillipa Soo',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 64},
 {'id': '5ivhfpfnoHhD8rUI2t3aJG',
  'track_name': 'IGNITE',
  'artist_name': 'Eir Aoi',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-06-24',
  'popularity': 57},
 {'id': '16sNPUamj4vnA7uQLozRpU',
  'track_name': 'Hurricane',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 64},
 {'id': '7cAexYA1vH6srKeIuKySud',
  'track_name': '超絶☆ダイナミック!',
  'artist_name': 'Kazuya Yoshii',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'single',
  'release_date': '2015-10-07',
  'popularity': 52},
 {'id': '40LYL1Z6xgCn5cBybo5K0D',
  'track_name': "It's Quiet Uptown",
  'artist_name': 'Renée Elise Goldsberry',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 65},
 {'id': '6KRHMYPIWRgFWlXPgqO2Fp',
  'track_name': 'Cabinet Battle #2',
  'artist_name': 'Christopher Jackson',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 65},
 {'id': '0P09TBGSKiQwfUsEh1UafT',
  'track_name': 'The World Was Wide Enough',
  'artist_name': 'Leslie Odom Jr.',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 65},
 {'id': '2bvbLvGD7YnS4Nhf9E4hUl',
  'track_name': 'Heartache',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 57},
 {'id': '3Ls7kkmVLU6MEqpB7lB3KS',
  'track_name': 'World Championship Finale 2 - From "Pitch Perfect 2" Soundtrack',
  'artist_name': 'The Barden Bellas',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'compilation',
  'release_date': '2015-05-11',
  'popularity': 49},
 {'id': '5L9MJsGqzTRD09rSzHkCDy',
  'track_name': 'Home',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 62},
 {'id': '6YTc18izaUvCS2XD7rK9Am',
  'track_name': 'Dance of Dragons',
  'artist_name': 'Ramin Djawadi',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-06-09',
  'popularity': 46},
 {'id': '3TfKt8mPpdXfQTMfRjHzyz',
  'track_name': 'Cabinet Battle #1',
  'artist_name': 'Christopher Jackson',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 66},
 {'id': '4EnswQiF7J5MsB18ElZSS2',
  'track_name': 'Esperanza Madre del Amor',
  'artist_name': 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015',
  'popularity': 25},
 {'id': '0Lc3coQTcMMJiiEFi7BG2z',
  'track_name': 'The Vagabond',
  'artist_name': 'Marcin Przybyłowicz',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-08-26',
  'popularity': 52},
 {'id': '0Iys022UwQ8xBfxE1g4nWZ',
  'track_name': 'One Last Time',
  'artist_name': 'Christopher Jackson',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 66},
 {'id': '5tmhUzJuP7XwqCHglyqnt8',
  'track_name': 'Geralt Of Rivia',
  'artist_name': 'Marcin Przybyłowicz',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-08-26',
  'popularity': 52},
 {'id': '2SGKT8dqAooD5vcF6HVsrR',
  'track_name': 'March of the Resistance',
  'artist_name': 'John Williams',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-12-18',
  'popularity': 26},
 {'id': '3PV4bPPqezu18K45MIOrVY',
  'track_name': 'Uwa!! So Temperate♫',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 59},
 {'id': '2ZR5DlUZBb4Mx2B4UZldgY',
  'track_name': "The Vikings are Told of Ragnar's Death",
  'artist_name': 'Trevor Morris',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-05-18',
  'popularity': 47},
 {'id': '0owIthsU5nNNPLK6MjdVOe',
  'track_name': 'Someone Loves Us',
  'artist_name': 'Dario Marianelli',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'compilation',
  'release_date': '2015-09-18',
  'popularity': 48},
 {'id': '36AhCvv8NAVPr0eNsv2PrW',
  'track_name': 'Ghost Fight',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 55},
 {'id': '3yY78aWyfri4ewOKIQokna',
  'track_name': 'The Wedding',
  'artist_name': 'Bear McCreary',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-02-10',
  'popularity': 47},
 {'id': '4QrLwgJt0OGkUFBbQKk0fL',
  'track_name': 'The Revenant Main Theme',
  'artist_name': 'Ryuichi Sakamoto',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-12-25',
  'popularity': 51},
 {'id': '2ydKgIVZAQXeYLWtxU8DFS',
  'track_name': 'Stay Alive - Reprise',
  'artist_name': 'Lin-Manuel Miranda',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 62},
 {'id': '6ZT36tXEKY2vvTCuNK4fi1',
  'track_name': 'Metal Crusher',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 55},
 {'id': '74HyNj8O7ytIgrdZBeb7mW',
  'track_name': 'The White Whale Chant',
  'artist_name': 'Roque Baños',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-12-04',
  'popularity': 43},
 {'id': '7Af5aQzfpm2VxnCFsy6Tkx',
  'track_name': 'Snowy',
  'artist_name': 'Toby Fox',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-15',
  'popularity': 57},
 {'id': '5mxTww2EuHbK0txi7U5C0A',
  'track_name': 'The Anvil of Crom (Form "CONAN THE BARBARIAN")',
  'artist_name': 'Basil Poledouris',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015',
  'popularity': 42},
 {'id': '68Ijc4fPmT3P5BN6Vrl2s2',
  'track_name': 'The Adams Administration',
  'artist_name': 'Original Broadway Cast of Hamilton',
  'year': 2015,
  'genre': 'soundtrack',
  'album_type': 'album',
  'release_date': '2015-09-25',
  'popularity': 64},

In [8]:
df = pd.DataFrame(lista_canciones) # Transformación en DataFrame

In [9]:
df

,id,track_name,artist_name,year,genre,album_type,release_date,popularity
0,1WHNqqRWhJVZIdCScFKtl5,Washington on Your Side,Leslie Odom Jr.,2015,soundtrack,album,2015-09-25,66
1,1DLfR4MOfLYbV6v3xrmWa8,We Know,Lin-Manuel Miranda,2015,soundtrack,album,2015-09-25,66
2,2AtC6i0b8TjpjhWBZYLprX,Bonetrousle,Toby Fox,2015,soundtrack,album,2015-09-15,58
3,6oF8ueLn5hIl4PRp17sxW6,That Would Be Enough,Phillipa Soo,2015,soundtrack,album,2015-09-25,67
4,46YSff2Rq1ZtN1YVk5cwbZ,Brave Shine,Aimer,2015,soundtrack,album,2015-07-29,61
...,...,...,...,...,...,...,...,...
2995,3qF8DcoQpQ1IXlMbTKHylP,Pull Up,Timaya,2019,afro,album,2019-02-08,46
2996,5wHi0nR9PGCygrfhSxI3Hq,Beginning,Joeboy,2019,afro,single,2019-08-16,44
2997,5iYqXLSwFkrsgXl53pAnhd,Boa Me (feat. Ed Sheeran & Mugeez),Fuse ODG,2019,afro,album,2019-03-08,41
2998,2H4JYNZrlnnRNxHd09AMYi,Killin Dem (feat. Zlatan),Burna Boy,2019,afro,album,2019-07-24,41
2999,3QGa7rzl3DFjLKnxGLLJ37,Tan Kalakatan - A COLORS SHOW,Mayra Andrade,2019,afro,single,2019-08-22,36

In [14]:
df.to_csv("Canciones_Spotify.csv", index=False) # Extración de datos a CSV

In [15]:
df_spotify = pd.read_csv("Canciones_Spotify.csv") # Lectura de CSV
df_spotify.head()

,id,track_name,artist_name,year,genre,album_type,release_date,popularity
0,1WHNqqRWhJVZIdCScFKtl5,Washington on Your Side,Leslie Odom Jr.,2015,soundtrack,album,2015-09-25,66
1,1DLfR4MOfLYbV6v3xrmWa8,We Know,Lin-Manuel Miranda,2015,soundtrack,album,2015-09-25,66
2,2AtC6i0b8TjpjhWBZYLprX,Bonetrousle,Toby Fox,2015,soundtrack,album,2015-09-15,58
3,6oF8ueLn5hIl4PRp17sxW6,That Would Be Enough,Phillipa Soo,2015,soundtrack,album,2015-09-25,67
4,46YSff2Rq1ZtN1YVk5cwbZ,Brave Shine,Aimer,2015,soundtrack,album,2015-07-29,61

In [16]:
Artistas_Spotify = df_spotify['artist_name'].tolist() # Creación de lista de artistas para ejecutar en archivo "artistas_LastFM.ipynb"

In [17]:
Artistas_Spotify

['Leslie Odom Jr.',
 'Lin-Manuel Miranda',
 'Toby Fox',
 'Phillipa Soo',
 'Aimer',
 'Original Broadway Cast of Hamilton',
 'Bear McCreary',
 'Fear, and Loathing in Las Vegas',
 'Okieriete Onaodowan',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Daveed Diggs',
 'Original Broadway Cast of Hamilton',
 'Leslie Odom Jr.',
 'Daveed Diggs',
 'Christopher Jackson',
 'Original Broadway Cast of Hamilton',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Jonathan Groff',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Phillipa Soo',
 'Toby Fox',
 'Jasmine Cephas-Jones',
 'Original Broadway Cast of Hamilton',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Leslie Odom Jr.',
 'Thayne Jasperson',
 'Leslie Odom Jr.',
 'KANA-BOON',
 'Michael Giacchino',
 'Leslie Odom Jr.',
 'Jonathan Groff',
 'Lin-Manuel Miranda',
 'Goose house',
 'Renée Elise Goldsberry',
 'John Williams',
 'Toby Fox',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Phillipa Soo',
 'Bear McCreary',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Toby Fox',
 'Ariana DeBose',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Michael Giacchino',
 'Phillipa Soo',
 'Eir Aoi',
 'Lin-Manuel Miranda',
 'Kazuya Yoshii',
 'Renée Elise Goldsberry',
 'Christopher Jackson',
 'Leslie Odom Jr.',
 'Toby Fox',
 'The Barden Bellas',
 'Toby Fox',
 'Ramin Djawadi',
 'Christopher Jackson',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'Marcin Przybyłowicz',
 'Christopher Jackson',
 'Marcin Przybyłowicz',
 'John Williams',
 'Toby Fox',
 'Trevor Morris',
 'Dario Marianelli',
 'Toby Fox',
 'Bear McCreary',
 'Ryuichi Sakamoto',
 'Lin-Manuel Miranda',
 'Toby Fox',
 'Roque Baños',
 'Toby Fox',
 'Basil Poledouris',
 'Original Broadway Cast of Hamilton',
 'Phillipa Soo',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Craig Armstrong',
 'Jonathan Groff',
 'Marcin Przybyłowicz',
 'Toby Fox',
 'Mikolai Stroinski',
 'BRADIO',
 'Lin-Manuel Miranda',
 'Donna Burke',
 'SIE Sound Team',
 'CHiCO with HoneyWorks',
 'Percival Schuttenbach',
 'Ólafur Arnalds',
 'Sho Oosawa',
 'Toby Fox',
 'Patrick Doyle',
 'Toby Fox',
 'Bear McCreary',
 'Peter Gregson',
 'Super DJ Yuuki',
 'Yutaka Yamada',
 'John Williams',
 'Toby Fox',
 'Harry Gregson-Williams',
 'Roque Baños',
 'Toby Fox',
 'Patrick Doyle',
 'James Newton Howard',
 'Aqua Timez',
 'SIE Sound Team',
 'Toby Fox',
 'Toby Fox',
 'GENERATIONS from EXILE TRIBE',
 'Patrick Doyle',
 'Mikolai Stroinski',
 'Toby Fox',
 'The Barden Bellas',
 'Das Sound Machine',
 'Toby Fox',
 'Dario Marianelli',
 'Virgen de los Reyes',
 'Bear McCreary',
 'Mikolai Stroinski',
 'Craig Armstrong',
 'Bear McCreary',
 'Toby Fox',
 'Toby Fox',
 'Marcin Przybyłowicz',
 'Mikolai Stroinski',
 'Toby Fox',
 'Virgen de los Reyes',
 'Toby Fox',
 'LiSA',
 'Toby Fox',
 'Konomi Suzuki',
 'Gareth Coker',
 'Bear McCreary',
 'Toby Fox',
 'Ramin Djawadi',
 'Yugo Kanno',
 'Geek Music',
 'Christopher Fitzgerald',
 'DEAN FUJIOKA',
 '3年E組うた担(渚&茅野&業&磯貝&前原)',
 'Yuki Hayashi',
 'RADWIMPS',
 'Ramin Djawadi',
 'Ramin Djawadi',
 'Crush',
 'James Newton Howard',
 'Piotr Musiał',
 'Kyle Dixon & Michael Stein',
 'Hans Zimmer',
 'THE ORAL CIGARETTES',
 'BURNOUT SYNDROMES',
 'Ryan Gosling',
 'Max Richter',
 'Fernando Velázquez',
 'RADWIMPS',
 'Hans Zimmer',
 'Ramin Djawadi',
 'Emma Stone',
 'Fernando Velázquez',
 'Max Richter',
 'MAN WITH A MISSION',
 'Ben Platt',
 'SID',
 'RADWIMPS',
 'MOB CHOIR',
 'Fernando Velázquez',
 'Emma Stone',
 'JAM Project',
 'John Legend',
 'Rupert Gregson-Williams',
 'Ryan Gosling',
 'Ryan Gosling',
 'Justin Hurwitz',
 'Kyle Dixon & Michael Stein',
 'La La Land Cast',
 'Ramin Djawadi',
 'Yuki Hayashi',
 'Fernando Velázquez',
 'Fernando Velázquez',
 'BURNOUT SYNDROMES',
 'Ramin Djawadi',
 'RADWIMPS',
 'Justin Hurwitz',
 'Ryan Gosling',
 'Ramin Djawadi',
 'Yugo Kanno',
 'CHEN',
 'Adrian Barba',
 'DAVICHI',
 'Hans Zimmer',
 'BUMP OF CHICKEN',
 '7!!',
 'Christopher Tin',
 'Kimiko Glenn',
 'YOON MIRAE',
 'Aests',
 'Adrian Barba',
 'GUMMY',
 'Ramin Djawadi',
 'Michael Giacchino',
 'エミリア(CV:高橋李依)',
 'Fernando Velázquez',
 'Yuki Hayashi',
 'Elmer Bernstein',
 'Ramin Djawadi',
 'RADWIMPS',
 'Hans Zimmer',
 'RADWIMPS',
 'Marcin Przybyłowicz',
 'Ramin Djawadi',
 'kensuke ushio',
 'Mikolai Stroinski',
 'Ramin Djawadi',
 '梶浦 由記',
 'amazarashi',
 'Rupert Gregson-Williams',
 'Nicholas Britell',
 'Haruka Tomatsu',
 'Yoko Shimomura',
 'Yoko Shimomura',
 'Piotr Musiał',
 'Henry Jackman',
 'Yuki Hayashi',
 'Ramin Djawadi',
 'Justin Hurwitz',
 '3年E組うた担(渚&茅野&業&磯貝&前原)',
 'Rupert Gregson-Williams',
 'Tina Guo',
 'Rupert Gregson-Williams',
 'James Newton Howard',
 'Yuki Hayashi',
 'Fernando Velázquez',
 'Rupert Gregson-Williams',
 'James Newton Howard',
 'Ramin Djawadi',
 'YOON MIRAE',
 'Jessie Mueller',
 'Ramin Djawadi',
 'Epik High',
 'Johan Söderqvist',
 'Cynthia Erivo',
 'Jessie Mueller',
 'Shiro SAGISU',
 'DAVICHI',
 'SOYOU',
 'Kyle Dixon & Michael Stein',
 'Thomas Newman',
 'Dessa',
 'Rupert Gregson-Williams',
 'Theodore Shapiro',
 'Ramin Djawadi',
 'Kyle Dixon & Michael Stein',
 'Chris Remo',
 'Sam Kim',
 'WEAVER',
 'Agrupación Musical Jesús Cautivo de Estepona',
 'Rupert Gregson-Williams',
 'Marcin Przybyłowicz',
 'Percival Schuttenbach',
 'Kyle Dixon & Michael Stein',
 'Tsuko G.',
 'Hans Zimmer',
 'Piotr Musiał',
 'Hans Zimmer',
 'Justin Hurwitz',
 'Henry Jackman',
 'Hans Zimmer',
 'SPYAIR',
 'Michael Giacchino',
 'RADWIMPS',
 'Amamiya Sora',
 'Sayuri',
 'Mick Gordon',
 'Max Richter',
 'LeeHi',
 'Chris Remo',
 'Henry Jackman',
 'Piotr Musiał',
 'RADWIMPS',
 'Craig Armstrong',
 'Max Richter',
 'Paolo Buonvino',
 'Johan Söderqvist',
 'The Meridian Studio Ensemble',
 'MYTH & ROID',
 'Mike Faist',
 'Lyn',
 'Lyn',
 'Sawano Hiroyuki',
 'Lyn',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'Bear McCreary',
 'Christy Altomare',
 'Christopher Larkin',
 'Christopher Larkin',
 'Hans Zimmer',
 'Animelmack',
 'amazarashi',
 'Charlie Clouser',
 'The Bellas',
 'Lyn',
 'Michelle Williams',
 'Linked Horizon',
 'Lyn',
 'Hugh Jackman',
 'Linked Horizon',
 'Ólafur Arnalds',
 'Christopher Larkin',
 'PornoGraffitti',
 'Linked Horizon',
 'Kenshi Yonezu',
 'Ben Platt',
 'Hugh Jackman',
 'Christopher Larkin',
 'Sawano Hiroyuki',
 'Ziv Zaifman',
 'Ramin Djawadi',
 'Hugh Jackman',
 'D-51',
 'Hans Zimmer',
 'Linked Horizon',
 'Christopher Larkin',
 'Loren Allred',
 'Zac Efron',
 'Christopher Larkin',
 'Keala Settle',
 'Christopher Larkin',
 'Hugh Jackman',
 'Loren Allred',
 'Keala Settle',
 'Austyn Johnson',
 'Zac Efron',
 'Hugh Jackman',
 'Ben Platt',
 'The Bellas',
 'Hans Zimmer',
 'AILEE',
 'The New Barden Bellas',
 'Tia',
 'Ben Platt',
 'The Bellas',
 'Yasuharu Takanashi',
 'Heize',
 'Ben Platt',
 'Kyle Dixon & Michael Stein',
 'Miura Jam',
 'deadman 死人',
 'MIYAVI',
 'Lyn',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'MYTH & ROID',
 'Sawano Hiroyuki',
 'Kiyoshi Hikawa',
 'The Bellas',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'MYTH & ROID',
 'Benjamin Wallfisch',
 'Yuki Hayashi',
 'Christopher Larkin',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Ramin Djawadi',
 'Christopher Larkin',
 'Rupert Gregson-Williams',
 'Ramin Djawadi',
 'Christopher Larkin',
 'Christopher Larkin',
 'Daniel Pemberton',
 'Christopher Larkin',
 'Hans Zimmer',
 'Lyn',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Christopher Larkin',
 'Hans Zimmer',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Ramin Djawadi',
 'アトラスサウンドチーム',
 'Laura Dreyfuss',
 'Chitose Morinaga',
 'Nostalghia',
 'GUMI',
 'Rachel Bay Jones',
 'Daniel Pemberton',
 'Anly',
 'Christy Altomare',
 'Angelo Badalamenti',
 'Sam Lee',
 'Kevin Penkin',
 'JUNNA',
 'Lyn',
 'NateWantsToBattle',
 'Lyn',
 'Rachel Bay Jones',
 'LiSA',
 'Ramin Djawadi',
 'Machico',
 'HENRY',
 'Machico',
 'Ryan Gosling',
 'cinema staff',
 'The Bellas',
 'アトラスサウンドチーム',
 'アトラスサウンドチーム',
 '岡部啓一',
 'Michael Giacchino',
 'Kristofer Maddigan',
 'Christopher Larkin',
 'Sawano Hiroyuki',
 'Hans Zimmer',
 'Angelo Badalamenti',
 'Yuki Hayashi',
 'Hans Zimmer',
 'Joris de Man',
 'La Sentencia',
 'Konomi Suzuki',
 'Hans Zimmer',
 'Konomi Suzuki',
 'Thomas Newman',
 'LiSA',
 'Sarah Schachner',
 'Christopher Larkin',
 'X-Ray Dog',
 'Brian the Sun',
 'Christopher Larkin',
 'The Bellas',
 'Christopher Larkin',
 'Aaron Montalvo',
 'Christopher Larkin',
 'UVERworld',
 '遠野高志',
 'Cher',
 'Hugh Skinner',
 'YOSHIKI',
 'SIX',
 'TK from Ling tosite sigure',
 'Toby Fox',
 'Toby Fox',
 'SIX',
 'Lily James',
 'Jeremy Irvine',
 'Toby Fox',
 'Linked Horizon',
 'Christopher Larkin',
 'Yugo Kanno',
 'Yugo Kanno',
 'Amanda Seyfried',
 'Toby Fox',
 'Amanda Seyfried',
 '物語シリーズ',
 'Justin Hurwitz',
 'Brian Tyler',
 'Lily James',
 'KANKAKU PIERO',
 'ムービー・サウンズ・アンリミテッド',
 'Lenny code fiction',
 '桜島麻衣(CV:瀬戸麻沙美)',
 'Cher',
 'MYTH & ROID',
 'Colin Firth',
 'VK Blanka',
 'Hugh Skinner',
 'ASIAN KUNG-FU GENERATION',
 'Lily James',
 'Christine Baranski',
 'Coda',
 'Amanda Seyfried',
 'Lily James',
 'James Newton Howard',
 'VK Blanka',
 'YOSHIKI',
 'Josh Dylan',
 'LiSA',
 'Manu Guix',
 'Manu Guix',
 'Creepy Nuts',
 'Trevor Jones',
 'Ben Platt',
 'Varian',
 'Kelly Clarkson',
 'SIX',
 'Ari Afsar',
 'Taylor Louderman',
 'Daichi Miura',
 'BiSH',
 'Kelly Clarkson',
 'SIX',
 'Geek Music',
 'Daniel Pemberton',
 'Toby Fox',
 'SIX',
 'Yoko Takahashi',
 'Lily James',
 'Berlinist',
 'Lily James',
 'Survive Said The Prophet',
 'Manu Guix',
 'Justin Hurwitz',
 'Toby Fox',
 'Christopher Larkin',
 'OxT',
 'Toby Fox',
 'Bradley Cooper',
 'Geoff Zanelli',
 'Manu Guix',
 'Bradley Cooper',
 'Ramin Djawadi',
 'Manu Guix',
 'いとうかなこ',
 'SID',
 'MAX',
 'Manu Guix',
 'Toby Fox',
 'Christopher Larkin',
 'Toby Fox',
 'Manu Guix',
 'Cher',
 'Lily James',
 'Manu Guix',
 'Bear McCreary',
 'Kumi Koda',
 'Justin Hurwitz',
 'Manu Guix',
 'SIX',
 'Toby Fox',
 'みゆな',
 'Manu Guix',
 'Dan Romer',
 'Friedrich Habetler',
 'Geek Music',
 'JEONG SEWOON',
 'Shonan No Kaze',
 'SIX',
 'SIX',
 'Berioska',
 'Kate Rockwell',
 'Grey Henson',
 'Friedrich Habetler',
 'ZAQ',
 'Hans Zimmer',
 'Toby Fox',
 'Manu Guix',
 'SIX',
 'Christopher Larkin',
 'Christopher Larkin',
 'Lena Raine',
 'Macarena García',
 'FLOW',
 'Evan Call',
 'Meryl Streep',
 'Linked Horizon',
 'Craig David',
 'FLOW',
 '桜島麻衣(CV:瀬戸麻沙美)',
 'Panos Mouzourakis',
 'The Flight',
 'Hans Zimmer',
 'Manu Guix',
 'vegeta',
 'Mili',
 'Toby Fox',
 'Bear McCreary',
 'Manu Guix',
 'Manu Guix',
 'Toby Fox',
 'Evan Call',
 'Manu Guix',
 'Friedrich Habetler',
 'Willow Sage Hart',
 'Akano',
 'The Rising Storm',
 '藤田真由美',
 'Toby Fox',
 'Olly Alexander (Years & Years)',
 'Manu Guix',
 'John Paesano',
 'Brian Tyler',
 'Alex Brightman',
 'Hildur Guðnadóttir',
 'Mika Nakashima',
 'MOB CHOIR',
 'André De Shields',
 'Hans Zimmer',
 'sumika',
 'Kyle Dixon & Michael Stein',
 '高橋\u3000洋子',
 'QUEEN BEE',
 'Ludwig Göransson',
 'coldrain',
 'Ramin Djawadi',
 'Cö shu Nie',
 'ALI',
 'Ramin Djawadi',
 'Casey Edwards',
 'ALI',
 'Alan Silvestri',
 '中野家の五つ子',
 'Mrs. GREEN APPLE',
 'UVERworld',
 'James Newton Howard',
 'Taron Egerton',
 'Hans Zimmer',
 'Thomas Newman',
 'Yugo Kanno',
 'UVERworld',
 'Ramin Djawadi',
 'Ramin Djawadi',
 'MAN WITH A MISSION',
 'Trevor Morris',
 'Seiko Oomori',
 'Thomas Newman',
 'Survive Said The Prophet',
 'Andrew Prahlow',
 '美波',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Andrew Prahlow',
 'Akano',
 'Ramin Djawadi',
 'Max Richter',
 'Linked Horizon',
 'Ramin Djawadi',
 'Linked Horizon',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Mrs. GREEN APPLE',
 'LiSA',
 'Carrie Hope Fletcher',
 'André De Shields',
 'Tricker',
 'Alex Brightman',
 'RoomTone',
 'Jamie Muscato',
 'Steven Universe',
 'FictionJunction',
 'Masayuki Suzuki',
 'DAVICHI',
 'YOON MIRAE',
 'Sophia Anne Caruso',
 'Vishal-Shekhar',
 'Trevor Morris',
 'Alan Silvestri',
 'Hans Zimmer',
 'Ramin Djawadi',
 '須田景凪',
 "T'Shan Williams",
 'John Powell',
 'Ludvig Forssell',
 'cinema staff',
 'Hans Zimmer',
 'Alan Silvestri',
 'Eva Noblezada',
 'Trevor Morris',
 'Ramin Djawadi',
 'Alex Brightman',
 'Steven Price',
 'Hiroshi Kitadani',
 'KANKAKU PIERO',
 'Andrew Prahlow',
 'Miyu Tomita',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'André De Shields',
 'Andrew Prahlow',
 'ASCA',
 'Max Richter',
 'Sawano Hiroyuki',
 'the peggies',
 'Hans Zimmer',
 'Hans Zimmer',
 'Hans Zimmer',
 'Akano',
 'Yugo Kanno',
 'Sawano Hiroyuki',
 'Hans Zimmer',
 'Andrew Prahlow',
 'MADKID',
 'LiSA',
 'King Gnu',
 'Hadestown Original Broadway Company',
 'Pawel Blaszczak',
 'Hadestown Original Broadway Company',
 'Hans Zimmer',
 'André De Shields',
 'UVERworld',
 'Taron Egerton',
 'Ricky Rojas',
 'Eva Noblezada',
 'RADWIMPS',
 'Hans Zimmer',
 'Hildur Guðnadóttir',
 'Sawano Hiroyuki',
 'Aaron Tveit',
 'Casey Edwards',
 'Hans Zimmer',
 'Alexandre Desplat',
 'Ramin Djawadi',
 'UVERworld',
 'Hans Zimmer',
 'Nicholas Britell',
 'ALI',
 'Hans Zimmer',
 'Kyle Dixon & Michael Stein',
 'Heize',
 'Thomas Newman',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Ramin Djawadi',
 'Danny Burstein',
 'Creepy Nuts',
 'Hans Zimmer',
 'MADKID',
 'Nicholas Britell',
 'Arijit Singh',
 'Andrew Prahlow',
 '10CM',
 'Reeve Carney',
 'Andrew Prahlow',
 'Andrew Prahlow',
 'Reeve Carney',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'EMPiRE',
 'Sawano Hiroyuki',
 'Marc Streitenfeld',
 'Clinton Shorter',
 'Hans Zimmer',
 'Akano',
 'Sawano Hiroyuki',
 'Collo',
 'Jay A',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Tereza Kesovija',
 'Группа 101',
 'Urbanus',
 'Đani Maršan',
 "Prajoth D'sa",
 'Krunoslav Kićo Slabinac',
 'Stan Van Samang',
 'Hari Rončević',
 'Datuk Ahmad Jais',
 'Badal Paul',
 'Группа 101',
 'Stan Van Samang',
 'Klapa Maslina',
 'Ivo Pattiera',
 'Lalitya Munshaw',
 'Группа 101',
 'Tereza Kesovija',
 'Sarah Ndagire',
 'Jay Jay',
 'Sarah Ndagire',
 'Krunoslav Kićo Slabinac',
 'Айкын',
 'Hari Rončević',
 'Tereza Kesovija',
 'Badal Paul',
 'Stimela',
 'Valeriya',
 'Badal Paul',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Krunoslav Kićo Slabinac',
 'Lalitya Munshaw',
 'Krunoslav Kićo Slabinac',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Klapa Puntamika',
 'Azad Amedê',
 'Cho Yong Pil',
 'Krunoslav-Kićo Slabinac',
 'Aidar BMM',
 'Jabu Khanyile',
 'Sarah Ndagire',
 'Tereza Kesovija',
 'Đani Maršan',
 'Айкын',
 'Park Mi Kyung',
 'Meri Cetinic',
 'Edita Sopjani',
 'Joo Yein',
 'Kwaya Ya Uinjilisti Ya Vijana Arusha Mjini',
 'Krunoslav Kićo Slabinac',
 'Krunoslav-Kićo Slabinac',
 'Lalitya Munshaw',
 'Lalitya Munshaw',
 'Đani Maršan',
 'Tamer Günaydın',
 'Aidar BMM',
 'Đani Maršan',
 'Dalmatino',
 'Lalitya Munshaw',
 'Meri Cetinic',
 'Cho Yong Pil',
 'Ivo Pattiera',
 'Klapa Puntamika',
 'Aidar BMM',
 'As One',
 'Hızır Acil',
 'Badal Paul',
 'Айкын',
 'Jabu Khanyile',
 'Đani Maršan',
 'Айкын',
 'Judith Sephuma',
 'Группа 101',
 'Dilnaz Akhmadiyeva',
 'Арай',
 'Hızır Acil',
 'Tomislav Ivčić',
 'Tural Everest',
 'Đani Maršan',
 'Afrigo Band',
 'Klapa Cambi',
 'Klapa Sufit',
 'Đani Maršan',
 'Meri Cetinic',
 'Tereza Kesovija',
 'Krunoslav Kićo Slabinac',
 'Tomislav Ivčić',
 'Tereza Kesovija',
 'Raj Negi',
 'Natali',
 'As One',
 'Stan Van Samang',
 'Арай',
 'Badal Paul',
 'Sarah Ndagire',
 'Raj Negi',
 'Badal Paul',
 'As One',
 'Sunny Hill',
 'Tereza Kesovija',
 'Stella Mengele',
 'Stan Van Samang',
 'Meri Cetinic',
 'Badal Paul',
 'Lissa Lewis',
 'Krunoslav Kićo Slabinac',
 'Sarah Ndagire',
 'Jay Jay',
 'Drain',
 'Valeriya',
 'Sarah Ndagire',
 'Jasna Zlokic',
 'Sarah Ndagire',
 'Aidar BMM',
 'Айкын',
 'Ivo Pattiera',
 'Herman Basudde',
 'Ivo Pattiera',
 'FauloCity',
 'Tomislav Bralic',
 'Krunoslav Kićo Slabinac',
 'Арай',
 'Jungyup',
 'Sarah Ndagire',
 'Meri Cetinic',
 'Afrigo Band',
 'Tedi Spalato',
 'Stan Van Samang',
 'Группа 101',
 'Vinko Coce',
 'Dinara Sultan',
 'Judith Sephuma',
 "Prajoth D'sa",
 'Jasna Zlokic',
 'Группа 101',
 'Krunoslav Kićo Slabinac',
 'Tereza Kesovija',
 'Krunoslav Kićo Slabinac',
 'Klapa Puntamika',
 'Tereza Kesovija',
 'Đani Maršan',
 'Lee Seung Chul',
 'Đani Maršan',
 'Suzy',
 'Арай',
 'Iwan Esseboom',
 'Amani',
 'Amani',
 'Flaka Krelani',
 'Lalitya Munshaw',
 'Klapa Cambi',
 'Tereza Kesovija',
 'Han All',
 'Meri Cetinic',
 'Tereza Kesovija',
 'Klapa Cambi',
 'Flaka Krelani',
 'Da Gudda Jazz',
 'Tomislav Ivčić',
 'Meri Cetinic',
 'Veli Sahiti',
 'Kim Young-Im',
 'Stan Van Samang',
 'Ruken',
 'Lee Mi Ja',
 'MAKTUB',
 '2LSON',
 'Remzie Osmani',
 'Jagmohan Digari',
 'Kim Young-Im',
 'Jasna Zlokic',
 'Naveen Pathak',
 'Lawrence P Dsouza',
 'Veli Sahiti',
 'OKDAL',
 'Naveen Pathak',
 'Naveen Pathak',
 'Stan Van Samang',
 'Tereza Kesovija',
 'Iwan Esseboom',
 'Tereza Kesovija',
 'Nam Jin',
 'Naveen Pathak',
 'Kim Young-Im',
 'Jay Jay',
 'Meri Cetinic',
 'Kim Young-Im',
 'Tereza Kesovija',
 'Meri Cetinic',
 'Koen Crucke',
 'Ivo Pattiera',
 'Gold Ag',
 'Stan Van Samang',
 'Amani',
 'Da Gudda Jazz',
 'Tereza Kesovija',
 'Meri Cetinic',
 'Ivo Pattiera',
 'Tereza Kesovija',
 'Tereza Kesovija',
 'Flaka Krelani',
 'Lissa Lewis',
 'Veli Sahiti',
 'Iwan Esseboom',
 'Klapa Sveti Juraj HRM',
 'Tereza Kesovija',
 'Bae Ho',
 'Nikolay Baskov',
 'Tereza Kesovija',
 'Stan Van Samang',
 'Meri Cetinic',
 'Kim Young-Im',
 'Sunny Hill',
 'Iwan Esseboom',
 'Jagmohan Digari',
 'Nikolay Baskov',
 'Lalitya Munshaw',
 'Kim Young-Im',
 'Lalitya Munshaw',
 'Patti Kim',
 'Lalitya Munshaw',
 'Kim Young-Im',
 'Koen Crucke',
 'Lee Mi Ja',
 'Klapa Iskon',
 'Tereza Kesovija',
 'Idiot Glee',
 'Natali',
 'Iwan Esseboom',
 'Lee Mi Ja',
 'Kim Young-Im',
 'Koen Crucke',
 'Tereza Kesovija',
 'Klapa Sufit',
 'Jeon Sang Keun',
 'Ronny Mosuse',
 'Vinko Coce',
 'Lawrence P Dsouza',
 'Veli Sahiti',
 'Flaka Krelani',
 'Klapa Sveti Juraj HRM',
 'Kim Young-Im',
 'Johan Kim',
 'Prelude',
 'Stan Van Samang',
 ...]